[toolchain]
anchor_version = "0.31.1"

[features]
seeds = false
skip-lint = false

[programs.devnet]
arcox_solana_router = "C7XUB3Ep67seiJAzz4Apeeus2AbxbnuqFzvodDWxqoTH"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"
